name: Trivy

on:
  workflow_dispatch:
  schedule:
    - cron: "30 20 * * *"

jobs:
  call_workflow:
    name: Run Trivy Scan Workflow
    uses: daneshk/ballerina-library/.github/workflows/security-scan-template.yml@test/daneshk-fork-run
    secrets: inherit
    with:
        additional-build-flags: "-x :mysql-examples:build"
